### PR TITLE
Add "eq" methods to Set and Dict

### PR DESCRIPTION
**Pull request by mavnn**

### CODE REVIEW

**Comment by mavnn** [comment]
I wasn't able to run tests locally, but these appear to work in the repl

**Comment by mavnn** [comment]
Food for thought: this implementation *might* return false for collections with the same elements if a different Sorter has been supplied. I don't see this as a problem, but I thought I'd flag it.

**Review by stoeffel — APPROVED** [review]
lgtm!

**Comment by rtfeldman** [comment]
Thanks @mavnn!

**Pull request merged**
